SchoolManagementSystem/Controllers/ExamTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace SchoolManagementSystem.Controllers
{
    public class ExamTablesController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();

        // GET: ExamTables
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var examTables = db.ExamTables.Include(e => e.UserTable);
            return View(examTables.ToList());
        }

        // GET: ExamTables/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTable examTable = db.ExamTables.Find(id);
            if (examTable == null)
            {
                return HttpNotFound();
            }
            return View(examTable);
        }

        // GET: ExamTables/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName");
            return View(new ExamTable());
        }

        // POST: ExamTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamTable examTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            examTable.UserID = userid;

            if (ModelState.IsValid)
            {
                db.ExamTables.Add(examTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examTable.UserID);
            return View(examTable);
        }

        // GET: ExamTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTable examTable = db.ExamTables.Find(id);
            if (examTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examTable.UserID);
            return View(examTable);
        }

        // POST: ExamTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamTable examTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            examTable.UserID = userid;
            if (ModelState.IsValid)
            {
                db.Entry(examTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", examTable.UserID);
            return View(examTable);
        }

        // GET: ExamTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamTable examTable = db.ExamTables.Find(id);
            if (examTable == null)
            {
                return HttpNotFound();
            }
            return View(examTable);
        }

        // POST: ExamTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            ExamTable examTable = db.ExamTables.Find(id);
            db.ExamTables.Remove(examTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagementSystem/Controllers/SendEmailController.cs
using DatabaseAccess;
using SchoolManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SchoolManagementSystem.Controllers
{
    public class SendEmailController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();
        // GET: Email
        public ActionResult Index()
        {
            return View(new SchoolManagementSystem.Models.SendEmail());
        }
        [HttpPost]
        public ActionResult Index(SendEmail email)
        {
            if (ModelState.IsValid)
            {

                var std = db.StudentTables.ToList();
                foreach (var item in std)
                {
                    WebMail.Send(item.EmailAddress,
                   email.Name,
                   email.Message,

                   null,
                   null
                   , null
                   , true
                   , null
                   , null
                   , null
                   , null
                   , null
                   , email.Emails);
                }

                var emp = db.StaffTables.ToList();
                foreach (var item in emp)
                {
                    WebMail.Send(item.EmailAddress,
                   email.Name,
                   email.Message,

                   null,
                   null
                   , null
                   , true
                   , null
                   , null
                   , null
                   , null
                   , null
                   , email.Emails);
                }


                return RedirectToAction("Mailsent");
            }
            return View();
        }
        public ActionResult Mailsent()
        {
            return View();
        }
    }
}

SchoolManagementSystem/Controllers/UserTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace SchoolManagementSystem.Controllers
{
    public class UserTablesController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();

        // GET: UserTables
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            var userTables = db.UserTables.Include(u => u.UserTypeTable);
            return View(userTables.ToList());
        }

        [HttpPost]
        public ActionResult Index(string usertypeids)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int? usertypeid = Convert.ToInt32(usertypeids);
            if (usertypeid > 0)
            {
                var userTables = db.UserTables.Where(e => e.UserTypeID == usertypeid);
                return View(userTables.ToList());
            }
            else {
                var userTables = db.UserTables.Include(u => u.UserTypeTable);
                return View(userTables.ToList());
            }

        }

        // GET: UserTables/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            return View(userTable);
        }

        // GET: UserTables/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.UserTypeID = new SelectList(db.UserTypeTables, "UserTypeID", "TypeName");
            return View(new UserTable());
        }

        // POST: UserTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserTable userTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.UserTables.Add(userTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserTypeID = new SelectList(db.UserTypeTables, "UserTypeID", "TypeName", userTable.UserTypeID);
            return View(userTable);
        }

        // GET: UserTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserTypeID = new SelectList(db.UserTypeTables, "UserTypeID", "TypeName", userTable.UserTypeID);
            return View(userTable);
        }

        // POST: UserTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,UserTypeID,FullName,UserName,Password,ContactNo,EmailAddress,Address")] UserTable userTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(userTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserTypeID = new SelectList(db.UserTypeTables, "UserTypeID", "TypeName", userTable.UserTypeID);
            return View(userTable);
        }

        // GET: UserTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserTable userTable = db.UserTables.Find(id);
            if (userTable == null)
            {
                return HttpNotFound();
            }
            return View(userTable);
        }

        // POST: UserTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            UserTable userTable = db.UserTables.Find(id);
            db.UserTables.Remove(userTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagementSystem/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystem.Controllers
{
    public class VideosController : Controller
    {
        // GET: Videos
        public ActionResult Index()
        {
            return View();
        }
    }
}

SchoolManagementSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "Home Screen";
}
@{

    int usertypeid = Convert.ToInt32(Convert.ToString(Session["UserTypeID"]));
    if (usertypeid == 1)
    {
        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header panel panel-success">
                        Student's
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "StudentTables")'>
                                    <i class="fas fa-user-graduate fa-2x"></i>
                                    <p>Add New Student</p>
                                </a>
                            </div>

                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "StudentPromotTables")'>
                                    <i class="fas fa-user fa-2x"></i>
                                    <p>Student Promote</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "ExamTables")'>
                                    <i class="fas fa-poll-h fa-2x"></i>
                                    <p>Students Exam</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "StudentTables")'>
                                    <i class="fas fa-user-friends fa-2x"></i>
                                    <p>Students List</p>
                                </a>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div class="col-md-6">


                <div class="card mb-4">
                    <div class="card-header">
                        Employee's
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "StaffTables")'>
                                    <i class="fas fa-user-tie fa-2x"></i>
                                    <p>Add New Employee</p>
                                </a>
                            </div>

                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "StaffAttendanceTables")'>
                                    <i class="fas fa-chart-line fa-2x"></i>
                                    <p>Staff Attendance</p>
                                </a>
                            </div>

                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "StaffTables")'>
                                    <i class="fas fa-users fa-2x"></i>
                                    <p>Employee List</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    }
}


<div class="row">
    @{

        int usertypeids = Convert.ToInt32(Convert.ToString(Session["UserTypeID"]));
        if (usertypeids == 1)
        {


            <div class="col-md-6">

                <div class="card mb-4">
                    <div class="card-header">
                        User's
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "UserTables")'>
                                    <i class="fas fa-user fa-2x"></i>
                                    <p>Add New User</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "UserTables")'>
                                    <i class="fas fa-users fa-2x"></i>
                                    <p>Users List</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    @{

        int usertypeida = Convert.ToInt32(Convert.ToString(Session["UserTypeID"]));
        if (usertypeida == 1 || usertypeida == 5)
        {
            <div class="col-md-6">

                <div class="card mb-4">
                    <div class="card-header">
                        Accounts and Finance
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "SubmissionFeeTables")'>
                                    <i class="fas fa-funnel-dollar fa-2x"></i>
                                    <p>Student Fee</p>
                                </a>
                            </div>
                            <div class="col-md-3  text-center">
                                <a href='@Url.Action("Create", "EmployeeSalaryTables")'>
                                    <i class="fas fa-funnel-dollar fa-2x"></i>
                                    <p>Staff Salaries</p>
                                </a>
                            </div>
                            <div class="col-md-3  text-center">
                                <a href='@Url.Action("Index", "ExpensesTables")'>
                                    <i class="fas fa-list fa-2x"></i>
                                    <p>Expenses</p>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>
@{
    int usertypeidas = Convert.ToInt32(Convert.ToString(Session["UserTypeID"]));
    if (usertypeidas == 1 || usertypeida == 2)
    {
        <div class="row">

            <div class="col-md-6">

                <div class="card mb-4">
                    <div class="card-header">
                        Operator Access
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "ExamMarksTables")'>
                                    <i class="fas fa-ellipsis-v fa-2x"></i>
                                    <p>Ganarate Exam</p>
                                </a>

                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "AttendanceTables")'>
                                    <i class="fas fa-list fa-2x"></i>
                                    <p>Student Attendance</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Create", "StaffAttendanceTables")'>
                                    <i class="fas fa-list fa-2x"></i>
                                    <p>Staff Attendance</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header">
                        Help & Support
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3 text-center">
                               <a href='@Url.Action("Index", "SendEmail")'>
                                    <i class="fas fa-desktop fa-2x"></i>
                                    <p>Email</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "SendEmailStaff")'>
                                    <i class="fas fa-sms fa-2x text-success"></i>
                                    <p>Staff Email</p>
                                </a>
                            </div>
                            <div class="col-md-3 text-center">
                                <a href='@Url.Action("Index", "Videos")'>
                                    <i class="far fa-eye fa-2x text-danger"></i>
                                    <p>Videos</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    }
}

SchoolManagementSystem/Views/Home/ChangePassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Change Password</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/AdminTemplate/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/AdminTemplate/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg- col-md-5">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body  ">
                        <!-- Nested Row within Card Body -->
                        <div class="p-6">
                            <div class="text-center">
                                <h1>Change Password</h1>
                                <h1 class="h4 text-gray-900 mb-4"><img alt="Dawn Cambridgy High School" src="~/Content/AdminTemplate/img/dawncambridge.png" width="160" height="160" /></h1>
                                 
                            </div>
                            <hr />
                            <h5 class="alert-danger">@ViewBag.message</h5>

                            @using (Html.BeginForm("ChangePasswordU", "Home", FormMethod.Post, new { @class = "form-horizontal user", role = "form", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" id="oldpassword" name="oldpassword" placeholder="Enter old Password...">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-user" id="newpassword" name="newpassword"  placeholder="Enter new Password...">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-user" id="confirmpassword" name="confirmpassword"  placeholder="Enter confirm Password...">
                                </div>
                                <input type="submit" value="Change Password" class="btn btn-success btn-user btn-block" />
                                <hr>

                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/AdminTemplate/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/AdminTemplate/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/AdminTemplate/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Content/AdminTemplate/js/sb-admin-2.min.js"></script>
</body>
</html>

SchoolManagementSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SchoolManagementSystem/Views/Home/ForgotPassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Change Password</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/AdminTemplate/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/AdminTemplate/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg- col-md-5">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body  ">
                        <!-- Nested Row within Card Body -->
                        <div class="p-6">
                            <div class="text-center">
                                <h1>Forgot Password</h1>
                                <h1 class="h4 text-gray-900 mb-4"><img alt="Dawn Cambridgy High School" src="~/Content/AdminTemplate/img/dawncambridge.png" width="160" height="160" /></h1>
                                 
                            </div>
                            <hr />
                            <h5 class="alert-danger">@ViewBag.message</h5>

                           @using (Html.BeginForm("ForgotPassword", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
                           {
                                @Html.AntiForgeryToken()

                                <div class="form-group">
                                    <input type="text" class="form-control form-control-user" id="email" name="email" placeholder="Enter Email...">
                                </div>
                                
                                <input type="submit" value="Send Password" class="btn btn-success btn-user btn-block" />
                                <hr>

                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/AdminTemplate/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/AdminTemplate/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/AdminTemplate/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Content/AdminTemplate/js/sb-admin-2.min.js"></script>
</body>
</html>