SchoolManagementSystem/Controllers/ExamReportsController.cs
using DatabaseAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManagementSystem.Controllers
{
    public class ExamReportsController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();
        // GET: ExamReports
        public ActionResult PrintDMC()
        {
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title");
            return View(new List<ExamMarksTable>());
        }


       [HttpPost()]
        public ActionResult PrintDMC(int? promoteid, int? examid)
        {
           
            ViewBag.ExamID = new SelectList(db.ExamTables, "ExamID", "Title");
            var promoterecord = db.StudentPromotTables.Find(promoteid);
            if (promoterecord != null)
            {

                var listmarks = db.ExamMarksTables.Where(e => e.ClassSubjectTable.ClassID == promoterecord.ClassID && e.ExamID == examid && e.StudentID == promoterecord.StudentID);
                if (listmarks != null)
                {

                }
                return View(listmarks);
            }
            
            return View(new List<ExamMarksTable>());
        }
    }
}

SchoolManagementSystem/Views/ExamReports/PrintDMC.cshtml
@model IEnumerable<DatabaseAccess.ExamMarksTable>


@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details Mark Sheet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

</head>
<body>
    <div class="form-group">
        <button type="button" class="btn btn-primary">Save Record</button>
        <a href="javascript:window.print()" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
        <a href='@Url.Action("SendEmail", "#")' class="btn btn-default"><i class="fas fa-envelope-open-text"></i>Email</a>
        </div>
        <br /><br />
        @using (Html.BeginForm("PrintDMC", "ExamReports", FormMethod.Post, new { @class = "form-horizontal user", role = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="col-md-10">
                Select Exam
                @Html.DropDownList("ExamID", null, htmlAttributes: new { @class = "form-control", @id = "examid", @name = "examid", @required = "required" })


            <div class="form-group">
                <label class="custom-control-label">Enter Promote ID</label>
                <input type="text" required class="form-control form-control-user" id="promoteid" name="promoteid">
            </div>
            <div class="form-group">
                <input type="submit" value="Get Report" class="btn btn-primary btn-user btn-block" />
            </div>
                </div>
        }
    <div class="align-content-md-center col-md-12">
        <div class="row">
            <div class="col-md-10">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="text-center"> <h1><b>DAWN CAMBRIDGE HIGH SCHOOL</b></h1></div>
                        <div class="text-center"><img src="~/Content/AdminTemplate/img/dawncambridge.png" height="200" width="220" /></div>
                        <div class="text-center"> <p>Afghan Colony Peshawar. Cell:0321-9113267</p></div>
                        <div class="text-center"><p> Affiliated With B.I.S.E. Peshawar.</p></div>
                        <div class="text-center"><h2><b>DETAIL MARKS CERTIFICATE</b></h2></div><br />
                        @*<div class="text-left"><p><b>Name: @Model.StudentTable.Name</b></p></div>*@
                        <br />
                        <div class="clearfix"></div>
                        <br />
                        @{
                        float totalmarks = 0;
                        float obtainmarks = 0;
                        float percentage = 0;
                        string grade;
                        }

                        <div class="container body-content">
                            <h5 class="alert-danger">@ViewBag.message</h5>

                            <table class="table table-striped table-condensed table-hover">
                                <tr>
                                    @*<th>
                                        Student
                                    </th>
                                    <th>
                                        Exam
                                    </th>*@
                                    <th>
                                        Subject
                                    </th>
                                    <th>
                                        Subject Total Marks
                                    </th>
                                    <th>
                                        Subject Obtain Marks
                                    </th>
                                    <th>
                                        User
                                    </th>

                                </tr>

                                @foreach (var item in Model)
                                {
                                    totalmarks = totalmarks + item.TotalMarks;
                                    obtainmarks = obtainmarks + item.ObtainMarks;
                                    percentage = item.ObtainMarks / item.TotalMarks * 100;
                                    //grade = "Your result is";

                                @*if(percentage <= 100 && percentage >= 80)

                                {
                                        <p>grade:A-1 - Excellent</p>
                                }


                                if (percentage <= 79 && percentage >= 70)

                                {
                                        <p>Grade:A - Very Good</p>
                                }

                                if (percentage <= 69 && percentage >= 60)

                                {
                                        <p>Grade:B - Good</p>
                                }

                                if (percentage <= 59 && percentage >= 50)

                                {
                                        <p>Grade:c - Fair</p>
                                }
                                if (percentage <= 49 && percentage >= 40)

                                {
                                        <p>Grade:D - Satisfactory</p>
                                }
                                if (percentage <= 39)

                                {
                                        <p>Fail</p>
                                }
                                else
                                {
                                        <p>There is no result</p>
                                }*@
                                    <tr>
                                        @*<td>
                                            @Html.DisplayFor(modelItem => item.StudentTable.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ExamTable.Title)
                                        </td>*@
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassSubjectTable.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TotalMarks)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ObtainMarks)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserTable.FullName)
                                        </td>

                                    </tr>
                            }

                            </table>
                            <div>
                                <label>Total Marks</label> @totalmarks;
                                <label>Obtain Marks</label> @obtainmarks:
                                <label>Percentage</label> @percentage: %
                                @*<label>Grade</label> @grade:*@
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>