SchoolManagementSystem/Controllers/ResumeController.cs
using AutoMapper;
using DatabaseAccess;
using SchoolManagementSystem.Repository;
using SchoolManagementSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;

namespace SchoolManagementSystem.Controllers
{
    public class ResumeController : Controller
    {
        private readonly IResumeRepository _resumeRepository;
        public ResumeController(IResumeRepository resumeRepository)
        {
            _resumeRepository = resumeRepository;
        }

        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CheckCV(int? id)
        {
            int employeeid = 0;
            if (id == null || id == 0)
            {

                int.TryParse(Convert.ToString(Session["EmployeeID"]), out employeeid);
            }
            else
            {
                employeeid = Convert.ToInt32(id);
                Session["EmployeeID"] = employeeid;
            }

            using (SchoolMgtDbEntities db = new SchoolMgtDbEntities())
            {
                var people = db.EmployeeResumeTables.Where(p => p.EmployeeID == employeeid);
                if (people != null)
                {
                    if (people.Count() > 0)
                    {
                        Session["EmployeeResumeID"] = _resumeRepository.GetIdPerson(employeeid);
                        return RedirectToAction("CV", new { id = employeeid });
                    }
                    else
                    {
                        return RedirectToAction("PersonnalInformtion");
                    }
                }
                else
                {
                    return RedirectToAction("PersonnalInformtion");
                }
            }
        }

        public ActionResult ViewCV(int? id)
        {
            return RedirectToAction("CV", new { id = id });
        }


        public ActionResult PersonnalInformtion()
        {
            return View();
        }


        [HttpGet]
        public ActionResult PersonnalInformtion(EmployeeResumeTableMV model)
        {
            //Nationality
            List<SelectListItem> nationality = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Pakistan", Value = "Pakistan", Selected = true},
            };


            //Educational Level
            List<SelectListItem> educationalLevel = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Hight School", Value = "Hight School", Selected = true},
                new SelectListItem { Text = "Diploma", Value = "Diploma"},
                new SelectListItem { Text = "Bachelor's degree", Value = "Bachelor's degree"},
                new SelectListItem { Text = "Master's degree", Value = "Master's degree"},
                new SelectListItem { Text = "Doctorate", Value = "Doctorate"},
            };

            model.ListNationality = nationality;
            model.ListEducationalLevel = educationalLevel;

            return View(model);
        }

        [HttpPost]
        [ActionName("PersonnalInformtion")]
        public ActionResult AddPersonnalInformtion(EmployeeResumeTableMV person)
        {
            var employeeid = 0;
            int.TryParse(Convert.ToString(Session["EmployeeID"]), out employeeid);
            int userid = 0;
            int.TryParse(Convert.ToString(Session["UserID"]), out userid);
            
            person.EmployeeID = employeeid;
            if (ModelState.IsValid)
            {
                //Creating Mapping
                Mapper.Initialize(cfg => cfg.CreateMap<EmployeeResumeTableMV, EmployeeResumeTable>());

                EmployeeResumeTable personEntity = Mapper.Map<EmployeeResumeTable>(person);
                personEntity.EmployeeID = employeeid;
                HttpPostedFileBase file = Request.Files["ImageProfil"];

                bool result = _resumeRepository.AddPersonnalInformation(personEntity, file);

                if (result)
                {

                    Session["EmployeeResumeID"] = _resumeRepository.GetIdPerson(employeeid);
                    return RedirectToAction("Education");
                }
                else
                {
                    ViewBag.Message = "Something Wrong !";
                    return View(person);
                }

            }

            ViewBag.MessageForm = "Please Check your form before submit !";
            return View(person);

        }

        public ActionResult OnlyEducation(int? id)
        {
            Session["EmployeeResumeID"] = _resumeRepository.GetIdPerson((int)id);
            if (Session["EmployeeResumeID"] == null)
            {
                return RedirectToAction("PersonnalInformtion");
            }
            return RedirectToAction("Education");
        }



        [HttpGet]
        public ActionResult Education(EmployeeEducationTableMV education)
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult AddOrUpdateEducation(EmployeeEducationTableMV education)
        {
            try
            {


                string msg = string.Empty;

                if (education != null)
                {
                    //Creating Mapping
                    Mapper.Reset();
                    Mapper.Initialize(cfg => cfg.CreateMap<EmployeeEducationTableMV, EmployeeEducationTable>());
                    EmployeeEducationTable educationEntity = Mapper.Map<EmployeeEducationTable>(education);
                    int userid = 0;
                    int.TryParse(Convert.ToString(Session["UserID"]), out userid);
                    educationEntity.UserID = userid;

                    int EmployeeResumeID = (int)Session["EmployeeResumeID"];

                    msg = _resumeRepository.AddOrUpdateEducation(educationEntity, EmployeeResumeID);

                }
                else
                {
                    msg = "Please re try the operation";
                }

                return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { data = "Undefined! please Try Again!" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public PartialViewResult EducationPartial(EmployeeEducationTableMV education)
        {

            education.ListOfCountry = GetCountries();
            education.ListOfCity = new List<SelectListItem>();
            education.ListOfCity.Add(new SelectListItem() { Text = "KPK", Value = "KPK", Selected = true });
            education.ListOfCity.Add(new SelectListItem() { Text = "Punjab", Value = "Punjab" });
            education.ListOfCity.Add(new SelectListItem() { Text = "Sindh", Value = "Sindh" });
            education.ListOfCity.Add(new SelectListItem() { Text = "Balochistan", Value = "Balochistan" });

            return PartialView("~/Views/Shared/_MyEducation.cshtml", education);
        }

        public ActionResult OnlyWorkExperience(int? id)
        {
            Session["EmployeeResumeID"] = _resumeRepository.GetIdPerson((int)id);
            if (Session["EmployeeResumeID"] == null)
            {
                return RedirectToAction("PersonnalInformtion");
            }
            return RedirectToAction("WorkExperience");
        }


        [HttpGet]
        public ActionResult WorkExperience()
        {
            return View();
        }

        public PartialViewResult WorkExperiencePartial(EmployeeWorkExperienceVM workExperience)
        {
            workExperience.ListeOfCountries = GetCountries();

            return PartialView("~/Views/Shared/_MyWorkExperience.cshtml", workExperience);
        }

        public ActionResult AddOrUpdateExperience(EmployeeWorkExperienceVM workExperience)
        {

            string msg = string.Empty;

            if (workExperience != null)
            {
                //Creating Mapping
                Mapper.Reset();
                Mapper.Initialize(cfg => cfg.CreateMap<EmployeeWorkExperienceVM, EmployeeWorkExperienceTable>());
                EmployeeWorkExperienceTable workExperienceEntity = Mapper.Map<EmployeeWorkExperienceTable>(workExperience);

                int EmployeeResumeID = (int)Session["EmployeeResumeID"];
                int userid = 0;
                int.TryParse(Convert.ToString(Session["UserID"]), out userid);
                workExperienceEntity.UserID = userid;
                workExperienceEntity.EmployeeResumeID = EmployeeResumeID;

                msg = _resumeRepository.AddOrUpdateExperience(workExperienceEntity, EmployeeResumeID);

            }
            else
            {
                msg = "Please re try the operation";
            }

            return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult OnlySkiCerfLang(int? id)
        {
            Session["EmployeeResumeID"] = _resumeRepository.GetIdPerson((int)id);
            if (Session["EmployeeResumeID"] == null)
            {
                return RedirectToAction("PersonnalInformtion");
            }
            return RedirectToAction("SkiCerfLang");
        }


        [HttpGet]
        public ActionResult SkiCerfLang()
        {
            return View();
        }

        public PartialViewResult SkillsPartial()
        {
            return PartialView("~/Views/Shared/_MySkills.cshtml");
        }

        public ActionResult AddSkill(EmployeeSkillsVM skill)
        {
            int EmployeeResumeID = (int)Session["EmployeeResumeID"];
            string msg = string.Empty;

            //Creating Mapping
            Mapper.Reset();
            Mapper.Initialize(cfg => cfg.CreateMap<EmployeeSkillsVM, EmployeeSkillTable>());

SchoolManagementSystem/Controllers/StaffTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace SchoolManagementSystem.Controllers
{
    public class StaffTablesController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();

        // GET: StaffTables
        public ActionResult Index()
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var staffTables = db.StaffTables.Include(s => s.DesignationTable).Include(s => s.UserTable);
            return View(staffTables.ToList());
        }

        // GET: StaffTables/Details/5
        public ActionResult Details(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffTable staffTable = db.StaffTables.Find(id);
            if (staffTable == null)
            {
                return HttpNotFound();
            }
            return View(staffTable);
        }

        // GET: StaffTables/Create
        public ActionResult Create()
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            ViewBag.DesignationID = new SelectList(db.DesignationTables, "DesignationID", "Title");
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName");
            return View(new StaffTable());
        }

        // POST: StaffTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StaffTable staffTable)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            
            staffTable.Photo = "/Content/EmployeePhoto/default.png";
            staffTable.UserID = 4;
            if (ModelState.IsValid)
            {
                var user = new UserTable();
                user.Address = staffTable.Address;
                user.ContactNo = staffTable.ContactNo;
                user.EmailAddress = staffTable.EmailAddress;
                user.FullName = staffTable.Name;
                user.UserName = staffTable.Name;
                user.UserTypeID = 6;
                user.Password = "8888";
                db.UserTables.Add(user);
                staffTable.UserID = user.UserID;
                db.StaffTables.Add(staffTable);
                db.SaveChanges();

                if (staffTable.PhotoFile != null)
                {
                    var folder = "/Content/EmployeePhoto";
                    var file = string.Format("{0}.png", staffTable.StaffID);
                    var response = FileHelper.UploadFile.UploadPhoto(staffTable.PhotoFile, folder, file);
                    if (response)
                    {
                        var pic = string.Format("{0}/{1}", folder, file);
                        staffTable.Photo = pic;
                        db.Entry(staffTable).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.DesignationID = new SelectList(db.DesignationTables, "DesignationID", "Title", staffTable.DesignationID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", staffTable.UserID);
            return View(staffTable);
        }

        // GET: StaffTables/Edit/5
        public ActionResult Edit(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffTable staffTable = db.StaffTables.Find(id);
            if (staffTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.DesignationID = new SelectList(db.DesignationTables, "DesignationID", "Title", staffTable.DesignationID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", staffTable.UserID);
            return View(staffTable);
        }

        // POST: StaffTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StaffTable staffTable)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }
            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            staffTable.UserID = userid;
            if (ModelState.IsValid)
            {
                
                var folder = "/Content/EmployeePhoto";
                var file = string.Format("{0}.png", staffTable.StaffID);
                var response = FileHelper.UploadFile.UploadPhoto(staffTable.PhotoFile, folder, file);
                if (response)
                {
                    var pic = string.Format("{0}/{1}", folder, file);
                    staffTable.Photo = pic;
                }

                db.Entry(staffTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DesignationID = new SelectList(db.DesignationTables, "DesignationID", "Title", staffTable.DesignationID);
            ViewBag.UserID = new SelectList(db.UserTables, "UserID", "FullName", staffTable.UserID);
            return View(staffTable);
        }

        // GET: StaffTables/Delete/5
        public ActionResult Delete(int? id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffTable staffTable = db.StaffTables.Find(id);
            if (staffTable == null)
            {
                return HttpNotFound();
            }
            return View(staffTable);
        }

        // POST: StaffTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            StaffTable staffTable = db.StaffTables.Find(id);
            db.StaffTables.Remove(staffTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolManagementSystem/Views/StaffTables/Create.cshtml
@model DatabaseAccess.StaffTable

@{
    ViewBag.Title = "Add Employee";
}


    <div class="card mb-4 shadow">
        <div class="card-header">
            Employee Information
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "StaffTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, "Enter Full Name", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.DesignationID, "Select Designation", htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownList("DesignationID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DesignationID, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })*@


                                @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label" })

                                <span class="btn btn-default btn-file">
                                    @Html.TextBoxFor(model => model.PhotoFile, new { type = "file" })
                                </span>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Gender, "Enter Gender", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        
                      
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Qualification, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Qualification, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Qualification, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ContactNo, "Contact No", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, "Status", htmlAttributes: new { @class = "control-label" })

                                <div class="checkbox">
                                    @Html.EditorFor(model => model.IsActive)
                                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                @Html.LabelFor(model => model.HomePhone, "Home Phone No", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="form-group">
                                @Html.LabelFor(model => model.EmailAddress, "Email Address", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.LabelFor(model => model.BasicSalary, "Basic Salary", htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.BasicSalary, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        
                    </div>
                   
                   
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Address, "Address", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @style = "resize: none; overflow-y:scroll;", rows = 5 } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                       
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Doyouhaveanydisability, "Do you have any disability?", htmlAttributes: new { @class = "control-label" })

                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Doyouhaveanydisability)
                                    @Html.ValidationMessageFor(model => model.Doyouhaveanydisability, "", new { @class = "text-danger" })
                                </div>

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Ifdisabilityyesthengiveusedtail, "If yes then give details", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Ifdisabilityyesthengiveusedtail, new { htmlAttributes = new { @class = "form-control", @style = "resize: none; overflow-y:scroll;", rows = 5 } })
                                @Html.ValidationMessageFor(model => model.Ifdisabilityyesthengiveusedtail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Areyoutakinganymedication, "Are you taking any medication?", htmlAttributes: new { @class = "control-label" })

                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Areyoutakinganymedication)
                                    @Html.ValidationMessageFor(model => model.Areyoutakinganymedication, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Ifmedicationyesthengiveusdetail, "If yes then give details", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Ifmedicationyesthengiveusdetail, new { htmlAttributes = new { @class = "form-control", @style = "resize: none; overflow-y:scroll;", rows = 5 } })
                                @Html.ValidationMessageFor(model => model.Ifmedicationyesthengiveusdetail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AnyCriminaloffcenceagainstyou, "Do you have any police record?", htmlAttributes: new { @class = "control-label" })

                                <div class="checkbox">
                                    @Html.EditorFor(model => model.AnyCriminaloffcenceagainstyou)
                                    @Html.ValidationMessageFor(model => model.AnyCriminaloffcenceagainstyou, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Ifcriminaloffcenceyesthengiveusdetail, "If yes then give details", htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Ifcriminaloffcenceyesthengiveusdetail, new { htmlAttributes = new { @class = "form-control", @style = "resize: none; overflow-y:scroll;", rows = 5 } })
                                @Html.ValidationMessageFor(model => model.Ifcriminaloffcenceyesthengiveusdetail, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-4">
                            <input type="submit" value="Save Record" class="btn btn-primary" />
                            @Html.ActionLink("Back", "Index")
                        </div>
                    </div>
                </div>
            }
        </div>
        </div>
    